import { Playfair_Display } from "next/font/google";
import "./globals.css";

const play = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={play.className}>{children}</body>
    </html>
  );
}
